/**
 * Blueprint and project data models for development plans
 */

import { ProductType, ComplexityLevel } from './common';
import { AgentStatus } from './agent';

// Individual section of a blueprint generated by an agent
export interface BlueprintSection {
  agent: string;
  title: string;
  content: string;
  keyPoints: string[];
  generatedAt: Date;
}

// Complete development blueprint containing all agent outputs
export interface Blueprint {
  id: string;
  softwareIdea: string;
  productType: ProductType;
  complexityLevel: ComplexityLevel;
  createdAt: Date;
  updatedAt: Date;
  sections: BlueprintSection[];
  metadata: {
    totalProcessingTime: number;
    agentCount: number;
    wordCount: number;
  };
}

// Project summary for history listing
export interface ProjectSummary {
  id: string;
  title: string;
  productType: ProductType;
  complexityLevel: ComplexityLevel;
  createdAt: Date;
  preview: string; // First 150 characters of software idea
  status: 'completed' | 'failed';
}

// Complete project data stored in local storage
export interface StoredProject {
  id: string;
  softwareIdea: string;
  productType: ProductType;
  complexityLevel: ComplexityLevel;
  blueprint: Blueprint;
  createdAt: string; // ISO string for JSON serialization
  agentStatuses: AgentStatus[];
}

// Blueprint generation metadata
export interface BlueprintMetadata {
  generatedBy: string; // DevCrew AI version
  apiVersion: string;
  processingStats: {
    startTime: Date;
    endTime: Date;
    totalDuration: number;
    agentTimings: Record<string, number>;
  };
  inputParameters: {
    softwareIdea: string;
    productType: ProductType;
    complexityLevel: ComplexityLevel;
  };
}

// Blueprint download configuration
export interface DownloadConfig {
  format: 'markdown' | 'pdf' | 'json';
  includeMetadata: boolean;
  includeTimestamps: boolean;
  filename?: string;
}